name: Testes Robot

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositório
      uses: actions/checkout@v3

    - name: Instalar Python e Dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install selenium

    - name: Executar Testes Robot
      run: robot tests/
